stages:
  - build
  - analyze
  - test

.ubuntu-amd64-bionic:
    image: registry.videolan.org/librist-ubuntu-bionic:20200501213126
    stage: build
    tags:
        - docker
        - amd64

.ubuntu-amd64-jammy:
    image: registry.videolan.org/libplacebo-ubuntu-jammy:20230730213642
    stage: build
    tags:
        - docker
        - amd64

.debian-amd64-common:
    image: registry.videolan.org/dav1d-debian-unstable:20200306210534
    stage: build
    tags:
        - docker
        - amd64

build-ubuntu:
    extends: .ubuntu-amd64-bionic
    tags:
        - docker
        - avx2
        - amd64
    script:
        - meson build --buildtype release --werror -Duse_tun=true
        - ninja -C build

build-win64:
    extends: .debian-amd64-common
    script:
        - wineserver -p && wine wineboot
        - meson build --buildtype release
                      --werror
                      --libdir lib
                      --cross-file common/ci/x86_64-w64-mingw32.meson
                      -Ddefault_library=both
                      -Duse_mbedtls=false
                      -Dhave_mingw_pthreads=true
        - ninja -C build
    artifacts:
        paths:
          - build
        expire_in: 24 hours

analyze-ubuntu:
    stage: analyze
    extends:
        - .ubuntu-amd64-bionic
    needs: ["build-ubuntu"]
    script:
        - meson build --buildtype release --werror -Dstatic_analyze=true
        - ninja -C build analyze
    dependencies: []

test-ubuntu:
    stage: test
    extends:
        - .ubuntu-amd64-jammy
    needs: ["build-ubuntu"]
    script:
        - meson build --buildtype release -Db_sanitize=address,undefined
        - cd build && meson test --print-errorlogs
    dependencies:
        - build-ubuntu
    artifacts:
        when: on_failure
        paths:
            - build/meson-logs/testlog.txt

